parameters:
#    polidog_backwork.example.class: Polidog\BackworkBundle\Example

services:
#    polidog_backwork.example:
#        class: %polidog_backwork.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
